version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/octo-login
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: octo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: octo-login
    volumes:
      - octo-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  octo-pgdata:
